apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: angularns
  labels:
    app: angular
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: gerrp/ln-angular:1.0
        ports:
        - containerPort: 80