apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flaskns
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: gerrp/ln-flask:1.0
        ports:
        - containerPort: 5000