apiVersion: v1
kind: Service
metadata:
  name: angular-nodeport
  namespace: angularns
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31001
      targetPort: 80
  type: NodePort