apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport
  namespace: flaskns
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 31000
      targetPort: 5000
  type: NodePort