apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeportAngular }}
  namespace: {{ .Values.namespaceAngular }}
spec: 
  selector:
    app: {{ .Values.imageAngular.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.containerAngular.port }}
      nodePort: {{ .Values.containerAngular.node }}
      targetPort: {{ .Values.containerAngular.port }}
  type: NodePort