name: ci-angular

on:
  push:
    branches:
      - "main"
    paths:
      - "angular-realworld-example-app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
            dockerfile: angular-realworld-example-app/dockerfile
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker build
        run: docker build ./angular-realworld-example-app -t ${{ secrets.DOCKERHUB_USERNAME }}/ln-angular:${{ github.run_number }}
        
      -
        name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ln-angular:${{ github.run_number }}
